name: UniverseMG
version: 1.0
authors: [SorryIm2Fresh, Mafrans]
main: com.Shadersoft.UniverseMG.UniverseMG

commands:
    universemg:
        description: Shows information about the plugin.
        usage: /<command>
        aliases: umg
    addadmin:
        description: Adds an admin.
        usage: /<command> <player> <rank>